{
 "title": "Prometheus Stats for Nvidia GPU",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU utilization",
   "type": "graph",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{instance=\"$server\"}",
     "legendFormat": "{{ gpu }}"
    }
   ]
  },
  {
   "title": "GPU temperature",
   "type": "graph",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory clock frequency (in MHz)",
   "type": "graph",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dcgm_memory_clock{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of double-bit persistent ECC errors",
   "type": "graph",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_dbe_aggregate_total{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of double-bit volatile ECC errors",
   "type": "graph",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_dbe_volatile_total{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of single-bit persistent ECC errors",
   "type": "graph",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_sbe_aggregate_total{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of single-bit volatile ECC errors",
   "type": "graph",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_ecc_sbe_volatile_total{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Decoder utilization",
   "type": "graph",
   "description": "Decoder utilization (in %)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_dec_utilization{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Encoder utilization (in %)",
   "type": "graph",
   "description": "Encoder utilization (in %)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_enc_utilization{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Framebuffer memory free (in MiB)",
   "type": "graph",
   "description": "Framebuffer memory free (in MiB)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_free{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Framebuffer memory used (in MiB)",
   "type": "graph",
   "description": "Framebuffer memory used (in MiB)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_used{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of PCIe retries.",
   "type": "graph",
   "description": "Total number of PCIe retries.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_pcie_replay_counter{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "graph",
   "description": "Power draw (in W)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Throttling duration due to power constraints",
   "type": "graph",
   "description": "Throttling duration due to power constraints (in us)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_violation{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of retired pages due to double-bit errors",
   "type": "graph",
   "description": "Total number of retired pages due to double-bit errors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_retired_pages_dbe{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of pages pending retirement",
   "type": "graph",
   "description": "Total number of pages pending retirement",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_retired_pages_pending{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Total number of retired pages due to single-bit errors",
   "type": "graph",
   "description": "Total number of retired pages due to single-bit errors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_retired_pages_sbe{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "SM clock frequency (in MHz)",
   "type": "graph",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_sm_clock{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Throttling duration due to thermal constraints",
   "type": "graph",
   "description": "Throttling duration due to thermal constraints (in us)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dcgm_thermal_violation{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Value of the last XID error encountered",
   "type": "graph",
   "description": "Value of the last XID error encountered",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_xid_errors{instance=\"$server\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  }
 ]
}